# Generated by Django 5.1.1 on 2024-10-13 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mydoc_api", "0003_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
